--删除数据
DELETE FROM TB_USERADMIN_USERROLEREL;
DELETE FROM TB_USERADMIN_USERORGANREL;
DELETE FROM TB_USERADMIN_USERGROUPREL;
DELETE FROM TB_USERADMIN_POPEDOM;
DELETE FROM TB_USERADMIN_GROUPROLEREL;
DELETE FROM TB_USERADMIN_RESOURCE;
DELETE FROM TB_USERADMIN_USER;
DELETE FROM TB_USERADMIN_USERGROUP;
DELETE FROM TB_USERADMIN_ORGAN;
DELETE FROM TB_USERADMIN_LOG;
DELETE FROM TB_USERADMIN_ROLE;
DELETE FROM TB_USERADMIN_SYSTEM;


--删除表
DROP TABLE TB_USERADMIN_USERROLEREL;
DROP TABLE TB_USERADMIN_USERORGANREL;
DROP TABLE TB_USERADMIN_USERGROUPREL;
DROP TABLE TB_USERADMIN_POPEDOM;
DROP TABLE TB_USERADMIN_GROUPROLEREL;
DROP TABLE TB_USERADMIN_RESOURCE;
DROP TABLE TB_USERADMIN_USER;
DROP TABLE TB_USERADMIN_USERGROUP;
DROP TABLE TB_USERADMIN_ORGAN;
DROP TABLE TB_USERADMIN_LOG;
DROP TABLE TB_USERADMIN_ROLE;
DROP TABLE TB_USERADMIN_SYSTEM; 
